config/routes.rb
Rails.application.routes.draw do

  resources :registered_applications

  devise_for :users

  namespace :api, defaults: { format: :json } do
    match '/events', to: 'events#preflight', via: [:options]
    resources :events, only: [:create]
  end

  get 'welcome/index'

  get 'welcome/show'

  root 'welcome#index'
end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :registered_application
end

app/models/registered_application.rb
class RegisteredApplication < ActiveRecord::Base
  belongs_to :user
  has_many :events
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

 has_many :registered_applications
end

app/controllers/api/events_controller.rb
class API::EventsController < ApplicationController
  skip_before_action :verify_authenticity_token
  skip_before_action :authenticate_user!
  before_filter :set_access_control_headers

  def set_access_control_headers
    headers['Access-Control-Allow-Origin'] = '*'
    headers['Access-Control-Allow-Methods'] = 'POST, GET, OPTIONS'
    headers['Access-Control-Allow-Headers'] = 'Content-Type'
  end

  def create
    Rails.logger.info ">>> I'm in create"
    Rails.logger.info ">>>> origin: #{request.env['HTTP_ORIGIN']}"
    registered_application = RegisteredApplication.find_by(url: request.env['HTTP_ORIGIN'])
    Rails.logger.info ">>>>>> #{registered_application.inspect}"
    if registered_application.nil?
      render json: "Unregistered Application", status: :unprocessable_entity
    else
      @event = registered_application.events.create(event_params)
        if @event.save
          render json: @event, status: :created
        else
          render json: {errors: @event.errors}, status: :unprocessable_entity
        end
    end
  end

  def preflight
    head 200
  end

  private

  def event_params
    params.require(:event).permit(:name)
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery prepend: true

  before_action :authenticate_user!

end

app/controllers/registered_applications_controller.rb
class RegisteredApplicationsController < ApplicationController
  before_action :find_id, only: [:show, :update, :edit, :destroy]
  def index
    @registered_applications = current_user.registered_applications
  end

  def show
    @events = @registered_application.events.group_by(&:name)
  end

  def edit

  end

  def update
    if @registered_application.update_attributes(app_params)
      flash[:notice] = "App updated and tracking"
      redirect_to @registered_application
    else
      flash.now[:alert] = "There was an error updating the app"
      render edit_registered_application_path(@registered_application)
    end
  end

  def new
    @registered_application = RegisteredApplication.new
  end

  def create
    @registered_application = current_user.registered_applications.new(app_params)

    if @registered_application.save
      flash[:notice] = "App saved and tracking"
      redirect_to @registered_application
    else
      flash.now[:alert] = "There was an error setting up app"
      render :new
    end
  end

  def destroy
    if @registered_application.destroy
      flash[:notice] ="\"#{@registered_application.name}\" was deleted"
      redirect_to registered_applications_path
    else
      flash.now[:alert] = "There was an error deleting the post."
      render :show
    end
  end

  private

  def find_id
    @registered_application = current_user.registered_applications.find(params[:id])
  end

  def app_params
    params.require(:registered_application).permit(:name, :URL)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    
  end

  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/registered_applications_helper.rb
module RegisteredApplicationsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blocmetrics</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
    <div class="container">
       <ul class="nav nav-tabs">
         <li><%= link_to "Home", welcome_index_path %></li>
         <li><%= link_to "My Apps", registered_applications_path %></li>
         <div class ='nav navbar-right'>
           <% if user_signed_in? %>
             Signed in as: <strong><%= current_user.email %></strong> |
             <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> - <%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
           <% else %>
             <%= link_to "Sign Up", new_user_registration_path, :class => 'navbar-link'  %> -
             <%= link_to "Sign In", new_user_session_path, :class => 'navbar-link'  %>
           <% end %>

         </div>
       </ul>

       <% if flash[:notice] %>
         <div class="alert alert-success">
           <button type="button" class="close" data-dismiss="alert">&times;</button>
           <%= flash[:notice] %>
         </div>
       <% elsif flash.now[:alert] %>
         <div class="alert alert-danger">
           <button type="button" class="close" data-dismiss="alert">&times;</button>
           <%= flash.now[:alert] %>
         </div>
       <% elsif flash[:alert] %>
         <div class="alert alert-warning">
           <button type="button" class="close" data-dismiss="alert">&times;</button>
           <%= flash[:alert] %>
         </div>
       <% end %>

       <%= yield %>
   </div>


</body>
</html>

app/views/registered_applications/_form.html.erb
<%= form_for (@registered_application) do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control', placeholder: "Name of App" %>
  </div>
  <div class="form-group">
    <%= f.label :URL %>
    <%= f.text_field :URL, class: 'form-control', placeholder: "URL of App" %>
  </div>
  <div class="form-group">
    <%= f.submit "Save", class: "btn btn-success" %>
  </div>
<% end %>

app/views/registered_applications/destroy.html.erb
<h1>RegisteredApplications#destroy</h1>
<p>Find me in app/views/registered_applications/destroy.html.erb</p>

app/views/registered_applications/edit.html.erb
<h1>Update <%= @registered_application.name %></h1>
<div class="row">
  <div class="col-md-4">
    <p> Please include : </p>
    <ul>
      <li>Name of the app to track</li>
      <li>URL of the app to be tracked</li>
    </ul>
  </div>
  <div class="col-md-8">
    <%= render partial: "form" %>
  </div>
</div>

app/views/registered_applications/index.html.erb
<h1>Current Registered Apps</h1>
<% @registered_applications.each do |app| %>
<p> <%= link_to app.name, app %>
<% end %>
<%= link_to "New App", new_registered_application_path, class: "btn btn-success" %>

app/views/registered_applications/new.html.erb
<h1>Register New App</h1>
<div class="row">
  <div class="col-md-4">
    <p> Please include : </p>
    <ul>
      <li>Name of the app to track</li>
      <li>URL of the app to be tracked</li>
    </ul>
  </div>
  <div class="col-md-8">
    <%= render partial: "form" %>
  </div>
</div>

app/views/registered_applications/show.html.erb
<h1><%= @registered_application.name %></h1>
<h2><%= @registered_application.URL %></h2>
  <p> Information about that App and functions go in here?</p>
  <p>
    <% @registered_application.events.each do |event| %>
    <ul>
      <li><%= event.name %></li>
    </ul>
    <% end %>
  </p>

  <p><%= link_to "Delete App", @registered_application, method: :delete, class: 'btn btn-danger', data: {confirm: "do you really want to do this?"} %></p>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>

app/views/welcome/show.html.erb
<h1>Welcome#show</h1>
<p>Find me in app/views/welcome/show.html.erb</p>